apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-adapter
  namespace: prometheus
data:
  config.yaml: |
    rules:
      - seriesQuery: 'http_requests_total{job="kubernetes-pods",app="scaletestapp"}'
        resources:
          overrides:
            namespace:
              resource: namespace
            pod:
              resource: pod
        name:
          matches: "http_requests_total"
          as: "http_requests_rps"
        metricsQuery: 'sum(rate(http_requests_total{job="kubernetes-pods",app="scaletestapp"}[3m])) by (<<.GroupBy>>)'
